name: faux-workshop-ci

on:
  pull_request:
    branches: [ master ]
    paths:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-workshop-ci.yaml
    - 'docs/**'

jobs:
  workshop-ci:
    runs-on: [ self-hosted, workflow-overhead ]
    steps:
    - run: 'echo "No build required" '
