name: workshop-ci

on:
  # run on pull request events for the master branch only
  pull_request:
    branches: [ master ]
    paths-ignore:
    - LICENSE
    - '**.md'
    - '.github/rulesets/**'
    - .github/workflows/run-crucible-tracking.yaml
    - .github/workflows/faux-crucible-ci.yaml
    - .github/workflows/faux-workshop-ci.yaml
    - 'docs/**'

  # allow for manual invocation from the actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/workshop-ci
  cancel-in-progress: true

jobs:
  workshop-ci:
    runs-on: [ self-hosted, workshop ]

    steps:
    - uses: actions/checkout@v4

    - name: Install git
      run: |
        sudo dnf install -y git

    - name: Install container dependencies
      run: |
        sudo dnf install -y skopeo podman buildah

    - name: Install Perl dependencies
      run: |
        sudo dnf install -y perl-Coro perl-JSON perl-JSON-XS perl-JSON-Validator perl-Data-UUID perl-Digest-SHA perl-Archive-Extract-xz-IO-Uncompress-UnXz.noarch

    - name: Install Toolbox
      run: |
        if [ -d ~/toolbox ]; then
          rm -Rf ~/toolbox
        fi
        pushd ~/
        git clone https://github.com/perftool-incubator/toolbox.git

    - name: Run workshop - dump-config
      run: |
        export TOOLBOX_HOME=~/toolbox
        echo
        sudo --preserve-env=TOOLBOX_HOME ./workshop.pl --log-level verbose --label workshop-ci-dump-config --userenv ./userenvs/fedora-ci.json --dump-config true

    - name: Run workshop - dump-config - force-build-policy missing
      run: |
        export TOOLBOX_HOME=~/toolbox
        echo
        sudo --preserve-env=TOOLBOX_HOME ./workshop.pl --log-level verbose --label workshop-ci-dump-config --userenv ./userenvs/fedora-ci.json --dump-config true --force-build-policy missing

    - name: Run workshop - dump-files
      run: |
        export TOOLBOX_HOME=~/toolbox
        echo
        sudo --preserve-env=TOOLBOX_HOME ./workshop.pl --log-level verbose --label workshop-ci-dump-files --userenv ./userenvs/fedora-ci.json --dump-files true

    - name: Run workshop
      run: |
        export TOOLBOX_HOME=~/toolbox
        echo
        sudo --preserve-env=TOOLBOX_HOME ./workshop.pl --log-level verbose --label workshop-ci --userenv ./userenvs/fedora-ci.json

    - name: Cleanup toolbox
      run: |
        rm -Rf ~/toolbox
